---
- name: Build Apache Web Servers
  hosts: localhost
  connection: local
  tasks:
   - name: ensure apache is installed
     apt: name=apache2 state=present

   - name: copy the latest hostfile
     copy: src=/etc/hosts dest=/etc/hosts

   - name: create a new user called sysadm
     user: name=sysadm password=password

   - name: ensure the apache2 web service is started
     service: name=apache2 state=started
